include: package:very_good_analysis/analysis_options.2.4.0.yaml
linter:
  rules:
    public_member_api_docs: false
    avoid_dynamic_calls: false
    sort_constructors_first: false
    require_trailing_commas: false
