name: cupid_test
description: My new Flutter app
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  bloc: ^7.2.1
  flutter:
    sdk: flutter
  flutter_bloc: ^7.3.3
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  cupertino_icons: ^1.0.4
  google_fonts: ^2.3.1
  equatable: ^2.0.3
  font_awesome_flutter: ^10.1.0
  dio: ^4.0.6
  flutter_screenutil: ^5.4.0+1
  shared_preferences: ^2.0.13
  firebase_core: ^1.15.0
  awesome_dialog: ^2.2.0
  cloud_firestore: ^3.1.13
  flutter_shimmer: ^2.1.2
  shimmer: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^2.4.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
  fonts:
    - family: ProductSans
      fonts:
        - asset: assets/fonts/ProductSans.ttf
    - family: Billabong
      fonts:
        - asset: assets/fonts/Billabong.ttf
